// =============================================================
// Building metadata — Pathfinder 2e Kingmaker structures
// =============================================================
// Source: Kingmaker AP / Archives of Nethys / Royal Kingdom Sheet
// Each entry's `itemBonuses` and `traditionBonuses` were cross-checked
// against the spreadsheet's Structures tab so the activity list matches
// what a player would see in the Settlements panel.
//
// This file no longer bundles any building artwork. Building images are
// loaded at runtime from <plugin folder>/building_images/<id>.png — see
// main.ts and the BUILDING_IMAGE_OVERRIDES map below. When no override
// exists for a building, the grid renders a placeholder name box instead.

import type { BuildingMetadata } from './types';

/**
 * Bundled building images — empty by design. Add runtime overrides via
 * BUILDING_IMAGE_OVERRIDES (populated by main.ts on plugin load).
 */
export const BUILDING_IMAGES: Record<string, string> = {};

// =============================================================
// Building dictionary
// =============================================================

export const BUILDINGS: Record<string, BuildingMetadata> = {
  academy: {
    id: 'academy',
    name: 'Academy',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE'],
    level: 10,
    lots: 2,
    residential: false,
    cost: '52 RP, 12 Lumber, 6 Luxuries, 12 Stone',
    construction: 'Scholarship (expert) DC 27',
    upgradeFrom: 'library',
    upgradeTo: 'military academy, university',
    ruin: '',
    description:
      "An academy gives your citizens — and the PCs themselves — an institution where advanced study in many fields can be pursued, researched, and referenced.",
    effects:
      "+2 item bonus to Lore checks to Recall Knowledge while Investigating, to Researching, and to Decipher Writing.",
    itemBonuses: [
      { activity: 'recall-knowledge-investigating', bonus: 2 },
      { activity: 'researching', bonus: 2 },
      { activity: 'decipher-writing', bonus: 2 },
      { activity: 'creative-solution', bonus: 2 },
    ],
    image: 'academy',
  },
  alchemylab: {
    id: 'alchemylab',
    name: 'Alchemy Laboratory',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '18 RP, 2 Ore, 5 Stone',
    construction: 'Industry (trained) DC 16',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description:
      "An alchemy laboratory serves as a factory for alchemists and their apprentices, crafting potions, elixirs, and alchemical items.",
    effects:
      "Treat the settlement's level as one higher for available alchemical items (stacks up to 3×). +1 item bonus to Identify Alchemy.",
    itemBonuses: [
      { activity: 'identify-alchemy', bonus: 1 },
      { activity: 'demolish', bonus: 1 },
    ],
    traditionBonuses: { alchemical: 1 },
    image: 'alchemylab',
  },
  arcanisttower: {
    id: 'arcanisttower',
    name: "Arcanist's Tower",
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 5,
    lots: 1,
    residential: false,
    cost: '30 RP, 6 Stone',
    construction: 'Magic (trained) DC 20',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Home and laboratory for an arcane spellcaster (usually a wizard), apprentices, servants, and students.",
    effects:
      "Treat settlement's level as one higher for available arcane magic items (stacks up to 3×). +1 item bonus to Borrow an Arcane Spell or Learn a Spell.",
    itemBonuses: [
      { activity: 'borrow-an-arcane-spell', bonus: 1 },
      { activity: 'learn-a-spell', bonus: 1 },
      { activity: 'quell-unrest-magic', bonus: 1 },
    ],
    traditionBonuses: { arcane: 1 },
    image: 'arcanisttower',
  },
  arena: {
    id: 'arena',
    name: 'Arena',
    type: 'STRUCTURE',
    tags: ['EDIFICE', 'YARD'],
    level: 9,
    lots: 4,
    residential: false,
    cost: '40 RP, 6 Lumber, 12 Stone',
    construction: 'Warfare (expert) DC 26',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A large public structure used to stage competitions, athletics, gladiatorial combats, and elaborate spectacles.",
    effects: "Retraining combat-themed feats here takes only 5 days rather than a week.",
    itemBonuses: [
      { activity: 'celebrate-holiday', bonus: 2 },
      { activity: 'quell-unrest-warfare', bonus: 2 },
    ],
  },
  bank: {
    id: 'bank',
    name: 'Bank',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 5,
    lots: 1,
    residential: false,
    cost: '28 RP, 4 Ore, 6 Stone',
    construction: 'Trade (trained) DC 20',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A secure building for storing valuables, granting loans, and collecting and transferring deposits.",
    effects: "Capital Investment can only be used within the influence area of a settlement with a bank.",
    itemBonuses: [{ activity: 'tap-treasury', bonus: 1 }],
    image: 'bank',
  },
  barracks: {
    id: 'barracks',
    name: 'Barracks',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'RESIDENTIAL'],
    level: 3,
    lots: 1,
    residential: true,
    cost: '6 RP, 2 Lumber, 1 Stone',
    construction: 'Defense DC 16',
    upgradeFrom: '',
    upgradeTo: 'garrison',
    ruin: '',
    description: "Houses and trains guards, militia, soldiers, and military forces.",
    effects: "First time built in any settlement, reduce Unrest by 1. Aids army recruitment and recovery.",
    itemBonuses: [
      { activity: 'garrison-army', bonus: 1 },
      { activity: 'recover-army', bonus: 1 },
      { activity: 'recruit-army', bonus: 1 },
    ],
    image: 'barracks',
  },
  brewery: {
    id: 'brewery',
    name: 'Brewery',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 1,
    lots: 1,
    residential: false,
    cost: '6 RP, 2 Lumber',
    construction: 'Agriculture DC 15',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Crafts alcohol — beer, wine, spirits — or nonalcoholic drinks.",
    effects: "When built, reduce Unrest by 1 (only while fewer than 4 breweries exist in the settlement).",
    itemBonuses: [{ activity: 'establish-trade-agreement', bonus: 1 }],
    image: 'brewery',
  },
  bridge: {
    id: 'bridge',
    name: 'Bridge',
    type: 'INFRASTRUCTURE',
    tags: [],
    level: 2,
    lots: 0,
    residential: false,
    cost: '6 RP, 1 Lumber or 1 Stone',
    construction: 'Engineering DC 16',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Bridges connect settlements with water borders to land. Built on a Water Border.",
    effects: "An island settlement with a bridge can provide influence; negates Trade penalty for island settlements.",
  },
  castle: {
    id: 'castle',
    name: 'Castle',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE', 'FAMOUS', 'INFAMOUS'],
    level: 9,
    lots: 4,
    residential: false,
    cost: '54 RP, 12 Lumber, 12 Stone',
    construction: 'Defense / Industry / Magic / Statecraft (expert) DC 26',
    upgradeFrom: 'town hall',
    upgradeTo: 'palace',
    ruin: '',
    description: "Fortified structure that often serves as the seat of government for a kingdom.",
    effects: "First built each Kingdom turn: reduce Unrest by 1d4. A castle in the capital allows 3 Leadership activities/turn.",
    itemBonuses: [
      { activity: 'new-leadership', bonus: 2 },
      { activity: 'pledge-of-fealty-statecraft', bonus: 2 },
      { activity: 'pledge-of-fealty-warfare', bonus: 2 },
      { activity: 'send-diplomatic-envoy', bonus: 2 },
      { activity: 'garrison-army', bonus: 2 },
      { activity: 'recover-army', bonus: 2 },
      { activity: 'recruit-army', bonus: 2 },
    ],
  },
  cathedral: {
    id: 'cathedral',
    name: 'Cathedral',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE', 'FAMOUS', 'INFAMOUS'],
    level: 15,
    lots: 4,
    residential: false,
    cost: '58 RP, 20 Lumber, 20 Stone',
    construction: 'Folklore (master) DC 34',
    upgradeFrom: 'temple',
    upgradeTo: '',
    ruin: '',
    description: "A focal point of spiritual worship and seat of regional religious power.",
    effects:
      "First built in a turn, reduce Unrest by 4. +3 to Lore/Religion to Recall Knowledge while Investigating and to faith Researching. Treat settlement level as 3 higher for divine items (does not stack with shrines/temples).",
    itemBonuses: [
      { activity: 'celebrate-holiday', bonus: 3 },
      { activity: 'provide-care', bonus: 3 },
      { activity: 'repair-reputation-corruption', bonus: 3 },
      { activity: 'recall-knowledge-investigating', bonus: 3 },
      { activity: 'research-faith', bonus: 3 },
    ],
    traditionBonuses: { divine: 3 },
  },
  cemetery: {
    id: 'cemetery',
    name: 'Cemetery',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 1,
    lots: 1,
    residential: false,
    cost: '4 RP, 1 Stone',
    construction: 'Folklore DC 15',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A plot of land set aside to bury the dead, possibly with above-ground vaults or catacombs.",
    effects: "Reduce Unrest gained from dangerous settlement events by 1 per cemetery (max 4).",
    image: 'cemetery',
  },
  constructionyard: {
    id: 'constructionyard',
    name: 'Construction Yard',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 10,
    lots: 4,
    residential: false,
    cost: '40 RP, 10 Lumber, 10 Stone',
    construction: 'Engineering DC 27',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A centralized place to gather supplies and craft components for larger building projects.",
    effects: "+1 item bonus to Build Structure and to Repair Reputation (Decay).",
    itemBonuses: [
      { activity: 'build-structure', bonus: 1 },
      { activity: 'repair-reputation-decay', bonus: 1 },
    ],
  },
  dump: {
    id: 'dump',
    name: 'Dump',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 2,
    lots: 1,
    residential: false,
    cost: '4 RP',
    construction: 'Industry DC 16',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A centralized place for the disposal of refuse, often with a caretaker's shack.",
    effects: "Some events impact settlements without a dump more harshly. Cannot share a block with Residential.",
    itemBonuses: [{ activity: 'demolish', bonus: 1 }],
    image: 'dump',
  },
  embassy: {
    id: 'embassy',
    name: 'Embassy',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 8,
    lots: 2,
    residential: false,
    cost: '26 RP, 10 Lumber, 6 Luxuries, 4 Stone',
    construction: 'Politics DC 24',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A place for diplomatic visitors to stay; bolsters international relations.",
    effects: "+1 item bonus to Send Diplomatic Envoy and Request Foreign Aid.",
    itemBonuses: [
      { activity: 'send-diplomatic-envoy', bonus: 1 },
      { activity: 'request-foreign-aid', bonus: 1 },
    ],
    image: 'embassy',
  },
  festivalhall: {
    id: 'festivalhall',
    name: 'Festival Hall',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '7 RP, 3 Lumber',
    construction: 'Arts DC 18',
    upgradeFrom: '',
    upgradeTo: 'theater',
    ruin: '',
    description: "A venue where performers entertain and citizens gather for celebrations.",
    effects: "+1 item bonus to Celebrate Holiday.",
    itemBonuses: [{ activity: 'celebrate-holiday', bonus: 1 }],
    image: 'festivalhall',
  },
  foundry: {
    id: 'foundry',
    name: 'Foundry',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 3,
    lots: 2,
    residential: false,
    cost: '16 RP, 5 Lumber, 2 Ore, 3 Stone',
    construction: 'Industry (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A facility used to refine ore into finished metal.",
    effects: "Each foundry increases your maximum Ore commodity capacity by 1. Cannot share a block with Residential.",
    itemBonuses: [{ activity: 'establish-work-site-mine', bonus: 1 }],
    image: 'foundry',
  },
  garrison: {
    id: 'garrison',
    name: 'Garrison',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'RESIDENTIAL'],
    level: 5,
    lots: 2,
    residential: true,
    cost: '28 RP, 6 Lumber, 3 Stone',
    construction: 'Warfare (trained) DC 20',
    upgradeFrom: 'barracks',
    upgradeTo: '',
    ruin: '',
    description: "A complex of barracks, training yards, and weapons storage for maintaining your military.",
    effects: "When built, reduce Unrest by 1.",
    itemBonuses: [
      { activity: 'outfit-army', bonus: 1 },
      { activity: 'train-army', bonus: 1 },
    ],
    image: 'garrison',
  },
  generalstore: {
    id: 'generalstore',
    name: 'General Store',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 1,
    lots: 1,
    residential: false,
    cost: '8 RP, 1 Lumber',
    construction: 'Trade DC 15',
    upgradeFrom: '',
    upgradeTo: 'luxury store, marketplace',
    ruin: '',
    description: "A place for citizens to purchase everyday supplies.",
    effects: "A settlement WITHOUT a general store or marketplace reduces effective level for purchases by 2.",
    image: 'generalstore',
  },
  granary: {
    id: 'granary',
    name: 'Granary',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 1,
    lots: 1,
    residential: false,
    cost: '12 RP, 2 Lumber',
    construction: 'Agriculture DC 15',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Silos and warehouses for storage of grain and other preserved foodstuffs.",
    effects: "Each granary increases your maximum Food commodity capacity by 1.",
    image: 'granary',
  },
  guildhall: {
    id: 'guildhall',
    name: 'Guildhall',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 5,
    lots: 2,
    residential: false,
    cost: '34 RP, 8 Lumber',
    construction: 'Trade (expert) DC 20',
    upgradeFrom: 'trade shop',
    upgradeTo: '',
    ruin: '',
    description: "Headquarters for a trade guild — offices, workshops, storefront.",
    effects: "+1 item bonus to related skill checks to Earn Income or to Repair.",
    itemBonuses: [{ activity: 'repair', bonus: 1 }],
    image: 'guildhall',
  },
  herbalist: {
    id: 'herbalist',
    name: 'Herbalist',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 1,
    lots: 1,
    residential: false,
    cost: '10 RP, 1 Lumber',
    construction: 'Wilderness DC 15',
    upgradeFrom: '',
    upgradeTo: 'hospital',
    ruin: '',
    description: "Small medicinal gardens and a storefront tended by those with knowledge of herbs.",
    effects: "+1 item bonus to Provide Care.",
    itemBonuses: [{ activity: 'provide-care', bonus: 1 }],
    image: 'herbalist',
  },
  hospital: {
    id: 'hospital',
    name: 'Hospital',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 9,
    lots: 2,
    residential: false,
    cost: '30 RP, 10 Lumber, 6 Stone',
    construction: 'Defense (expert) DC 26',
    upgradeFrom: 'herbalist',
    upgradeTo: '',
    ruin: '',
    description: "A building dedicated to healing the sick through both magical and mundane means.",
    effects: "+2 item bonus to Medicine checks to Treat Disease and Treat Wounds.",
    itemBonuses: [
      { activity: 'treat-disease', bonus: 2 },
      { activity: 'treat-wounds', bonus: 2 },
      { activity: 'provide-care', bonus: 2 },
    ],
    image: 'hospital',
  },
  houses: {
    id: 'houses',
    name: 'Houses',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'RESIDENTIAL'],
    level: 1,
    lots: 1,
    residential: true,
    cost: '3 RP, 1 Lumber',
    construction: 'Industry DC 15',
    upgradeFrom: 'tenement',
    upgradeTo: 'mansion, orphanage',
    ruin: '',
    description: "A neighborhood of single and multi-family dwellings for your citizens.",
    effects: "First houses built each Kingdom turn: reduce Unrest by 1.",
    image: 'houses',
  },
  illicitmarket: {
    id: 'illicitmarket',
    name: 'Illicit Market',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'INFAMOUS'],
    level: 6,
    lots: 1,
    residential: false,
    cost: '50 RP, 5 Lumber',
    construction: 'Intrigue (trained) DC 22',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '+1 Crime',
    description: "A facade of innocent-seeming shops covering unregulated and illegal trade.",
    effects: "Treat settlement's level as one higher for available items (stacks up to 3×).",
    itemBonuses: [{ activity: 'clandestine-business', bonus: 1 }],
    traditionBonuses: { base: 1 },
    image: 'illicitmarket',
  },
  inn: {
    id: 'inn',
    name: 'Inn',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'RESIDENTIAL'],
    level: 1,
    lots: 1,
    residential: true,
    cost: '10 RP, 2 Lumber',
    construction: 'Trade DC 15',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A safe and secure place for a settlement's visitors to rest.",
    effects: "+1 item bonus to Hire Adventurers.",
    itemBonuses: [{ activity: 'hire-adventurers', bonus: 1 }],
    image: 'inn',
  },
  jail: {
    id: 'jail',
    name: 'Jail',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 2,
    lots: 1,
    residential: false,
    cost: '14 RP, 4 Lumber, 2 Ore, 4 Stone',
    construction: 'Defense DC 16',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A fortified structure that houses criminals, prisoners, or dangerous monsters.",
    effects: "First jail built each Kingdom turn: reduce Crime by 1.",
    itemBonuses: [{ activity: 'quell-unrest-intrigue', bonus: 1 }],
    image: 'jail',
  },
  keep: {
    id: 'keep',
    name: 'Keep',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE'],
    level: 3,
    lots: 2,
    residential: false,
    cost: '32 RP, 8 Lumber, 8 Stone',
    construction: 'Defense (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A high-walled defensive structure that guards the heart of a settlement.",
    effects: "First keep built each Kingdom turn: reduce Unrest by 1.",
    itemBonuses: [
      { activity: 'deploy-army', bonus: 1 },
      { activity: 'garrison-army', bonus: 1 },
      { activity: 'train-army', bonus: 1 },
    ],
    image: 'keep',
  },
  library: {
    id: 'library',
    name: 'Library',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 2,
    lots: 1,
    residential: false,
    cost: '6 RP, 4 Lumber, 2 Stone',
    construction: 'Scholarship (trained) DC 16',
    upgradeFrom: '',
    upgradeTo: 'academy',
    ruin: '',
    description: "Collections of books, scrolls, writings, and records conducive to research.",
    effects: "+1 item bonus to Lore checks to Recall Knowledge while Investigating, to Researching, and to Decipher Writing.",
    itemBonuses: [
      { activity: 'recall-knowledge-investigating', bonus: 1 },
      { activity: 'researching', bonus: 1 },
      { activity: 'decipher-writing', bonus: 1 },
      { activity: 'rest-and-relax-scholarship', bonus: 1 },
    ],
    image: 'library',
  },
  lumberyard: {
    id: 'lumberyard',
    name: 'Lumberyard',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 3,
    lots: 2,
    residential: false,
    cost: '16 RP, 5 Lumber, 1 Ore',
    construction: 'Industry (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "An open area to store lumber, with a mill to process it into building timber.",
    effects: "Each lumberyard increases maximum Lumber commodity capacity by 1. Must be built next to a Water border.",
    itemBonuses: [{ activity: 'establish-work-site-lumber-camp', bonus: 1 }],
    image: 'lumberyard',
  },
  luxurystore: {
    id: 'luxurystore',
    name: 'Luxury Store',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 6,
    lots: 1,
    residential: false,
    cost: '28 RP, 10 Lumber, 6 Luxuries',
    construction: 'Trade (expert) DC 22',
    upgradeFrom: 'general store',
    upgradeTo: 'magic shop',
    ruin: '',
    description: "Stores specializing in expensive, rare, and exotic goods that cater to the wealthy.",
    effects: "Must be built on a block with a mansion or noble villa. Treat level as one higher for luxury-themed magic items (stacks up to 3×).",
    itemBonuses: [{ activity: 'establish-trade-agreement', bonus: 1 }],
    traditionBonuses: { luxurious: 1 },
    image: 'luxurystore',
  },
  magicshop: {
    id: 'magicshop',
    name: 'Magic Shop',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 8,
    lots: 1,
    residential: false,
    cost: '44 RP, 8 Lumber, 6 Luxuries, 6 Stone',
    construction: 'Magic (expert) DC 24',
    upgradeFrom: 'luxury store',
    upgradeTo: 'occult shop',
    ruin: '',
    description: "Specializes in magic items and connecting buyers with sellers of magical goods and services.",
    effects: "Treat level as one higher for available magic items (stacks up to 3×).",
    itemBonuses: [{ activity: 'supernatural-solution', bonus: 1 }],
    // Magic Shop boosts magic items broadly; we model it as a base bump.
    traditionBonuses: { base: 1 },
    image: 'magicshop',
  },
  magicalstreetlamps: {
    id: 'magicalstreetlamps',
    name: 'Magical Streetlamps',
    type: 'INFRASTRUCTURE',
    tags: [],
    level: 5,
    lots: 0,
    residential: false,
    cost: '20 RP',
    construction: 'Magic (expert) DC 20',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Everburning torches fitted within lampposts along the streets.",
    effects: "Provides nighttime illumination for the entire Urban Grid. First built in a turn: reduce Crime by 1.",
  },
  mansion: {
    id: 'mansion',
    name: 'Mansion',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'RESIDENTIAL'],
    level: 5,
    lots: 1,
    residential: true,
    cost: '10 RP, 6 Lumber, 6 Luxuries, 3 Stone',
    construction: 'Industry (trained) DC 20',
    upgradeFrom: 'houses',
    upgradeTo: 'noble villa',
    ruin: '',
    description: "A larger manor house housing a wealthy family.",
    effects: "+1 item bonus to Improve Lifestyle.",
    itemBonuses: [{ activity: 'improve-lifestyle', bonus: 1 }],
    image: 'mansion',
  },
  marketplace: {
    id: 'marketplace',
    name: 'Marketplace',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'RESIDENTIAL'],
    level: 4,
    lots: 2,
    residential: true,
    cost: '48 RP, 4 Lumber',
    construction: 'Trade (trained) DC 19',
    upgradeFrom: 'general store',
    upgradeTo: '',
    ruin: '',
    description: "A neighborhood of shops and an open area for traveling merchants and farmers.",
    effects: "+1 item bonus to Establish Trade Agreement.",
    itemBonuses: [{ activity: 'establish-trade-agreement', bonus: 1 }],
    image: 'marketplace',
  },
  menagerie: {
    id: 'menagerie',
    name: 'Menagerie',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE'],
    level: 12,
    lots: 4,
    residential: false,
    cost: '26 RP, 14 Lumber, 10 Ore, 10 Stone',
    construction: 'Wilderness (expert) DC 30',
    upgradeFrom: 'park',
    upgradeTo: '',
    ruin: '',
    description: "A large zoo with numerous enclosures, exhibits, tanks, or open preserves.",
    effects: "Capturing a creature of level 6+ (kingdom level ≥ creature level + 4) and adding it grants 1 Fame/Infamy or reduces a Ruin by 1. Sapient creatures add 1 Unrest/turn.",
    itemBonuses: [{ activity: 'rest-and-relax-wilderness', bonus: 2 }],
  },
  militaryacademy: {
    id: 'militaryacademy',
    name: 'Military Academy',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE'],
    level: 12,
    lots: 2,
    residential: false,
    cost: '36 RP, 12 Lumber, 6 Ore, 10 Stone',
    construction: 'Warfare (expert) DC 30',
    upgradeFrom: 'academy',
    upgradeTo: '',
    ruin: '',
    description: "Dedicated to the study of war and the training of elite soldiers and officers.",
    effects: "+2 item bonus to Pledge of Fealty using Warfare, and +2 item bonus to Train Army.",
    itemBonuses: [
      { activity: 'pledge-of-fealty-warfare', bonus: 2 },
      { activity: 'train-army', bonus: 2 },
    ],
  },
  mill: {
    id: 'mill',
    name: 'Mill',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 2,
    lots: 1,
    residential: false,
    cost: '6 RP, 2 Lumber, 1 Stone',
    construction: 'Industry (trained) DC 16',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Grinds grain using wind, water, or beasts of burden.",
    effects: "If at least one mill is built on a lot adjacent to a Water border, reduce Consumption by 1 (min 0).",
    itemBonuses: [{ activity: 'harvest-crops', bonus: 1 }],
    image: 'mill',
  },
  mint: {
    id: 'mint',
    name: 'Mint',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE'],
    level: 15,
    lots: 1,
    residential: false,
    cost: '30 RP, 12 Lumber, 20 Ore, 16 Stone',
    construction: 'Trade (master) DC 34',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Allows the kingdom to produce its own coinage; can include a fortified treasury.",
    effects: "+3 item bonus to Capital Investment, Collect Taxes, and Repair Reputation (Crime).",
    itemBonuses: [
      { activity: 'capital-investment', bonus: 3 },
      { activity: 'collect-taxes', bonus: 3 },
      { activity: 'repair-reputation-crime', bonus: 3 },
    ],
    image: 'mint',
  },
  monument: {
    id: 'monument',
    name: 'Monument',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '6 RP, 1 Stone',
    construction: 'Arts (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "An impressive stone structure commemorating an event, leader, tragedy, or simply art.",
    effects: "First monument each Kingdom turn: reduce Unrest by 1 and reduce one Ruin of choice by 1.",
    image: 'monument',
  },
  museum: {
    id: 'museum',
    name: 'Museum',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'FAMOUS', 'INFAMOUS'],
    level: 5,
    lots: 2,
    residential: false,
    cost: '30 RP, 6 Lumber, 2 Stone',
    construction: 'Exploration (trained) DC 20',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Displays art, cultural objects, natural wonders, and other marvels.",
    effects: "Donating a magic item of level 6+ reduces Unrest by 1 (removing it raises Unrest by 1).",
    itemBonuses: [{ activity: 'rest-and-relax-arts', bonus: 1 }],
  },
  noblevilla: {
    id: 'noblevilla',
    name: 'Noble Villa',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'RESIDENTIAL'],
    level: 9,
    lots: 2,
    residential: true,
    cost: '24 RP, 10 Lumber, 6 Luxuries, 8 Stone',
    construction: 'Politics (expert) DC 19',
    upgradeFrom: 'mansion',
    upgradeTo: '',
    ruin: '',
    description: "A sprawling manor with luxurious grounds, housing a noble family and staff.",
    effects: "First noble villa each Kingdom turn: reduce Unrest by 2.",
    itemBonuses: [
      { activity: 'improve-lifestyle', bonus: 1 },
      { activity: 'quell-unrest-politics', bonus: 1 },
    ],
  },
  occultshop: {
    id: 'occultshop',
    name: 'Occult Shop',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 13,
    lots: 1,
    residential: false,
    cost: '68 RP, 12 Lumber, 12 Luxuries, 6 Stone',
    construction: 'Magic (master) DC 32',
    upgradeFrom: 'magic shop',
    upgradeTo: '',
    ruin: '',
    description: "A mysterious store specializing in obscure magic and curios, often offering supernatural services.",
    effects: "Treat level as one higher for available magic items (stacks up to 3×). +2 item bonus to Research esoteric subjects or Recall Knowledge on those topics.",
    itemBonuses: [
      { activity: 'recall-knowledge-esoteric', bonus: 2 },
      { activity: 'research-esoteric', bonus: 2 },
      { activity: 'prognostication', bonus: 2 },
    ],
    traditionBonuses: { base: 1 },
    image: 'occultshop',
  },
  operahouse: {
    id: 'operahouse',
    name: 'Opera House',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE', 'FAMOUS', 'INFAMOUS'],
    level: 15,
    lots: 2,
    residential: false,
    cost: '40 RP, 20 Lumber, 18 Luxuries, 16 Stone',
    construction: 'Arts (master) DC 34',
    upgradeFrom: 'theater',
    upgradeTo: '',
    ruin: '',
    description: "A venue for operas, plays, and concerts, with extensive bardic training facilities.",
    effects: "First opera house each Kingdom turn: reduce Unrest by 4. +3 item bonus to Performance to Earn Income.",
    itemBonuses: [
      { activity: 'performance-earn-income', bonus: 3 },
      { activity: 'celebrate-holiday', bonus: 3 },
      { activity: 'create-a-masterpiece', bonus: 3 },
    ],
  },
  orphanage: {
    id: 'orphanage',
    name: 'Orphanage',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'RESIDENTIAL'],
    level: 2,
    lots: 1,
    residential: true,
    cost: '6 RP, 2 Lumber',
    construction: 'Industry DC 16',
    upgradeFrom: 'houses',
    upgradeTo: '',
    ruin: '',
    description: "Provides housing for orphans and homeless citizens, also aiding refugees.",
    effects: "First orphanage each Kingdom turn: reduce Unrest by 1.",
    image: 'orphanage',
  },
  palace: {
    id: 'palace',
    name: 'Palace',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE', 'FAMOUS', 'INFAMOUS'],
    level: 15,
    lots: 4,
    residential: false,
    cost: '108 RP, 20 Lumber, 12 Luxuries, 15 Ore, 20 Stone',
    construction: 'Defense / Industry / Magic / Statecraft (master) DC 34',
    upgradeFrom: 'castle',
    upgradeTo: '',
    ruin: '',
    description: "A grand and splendid seat of government for your leaders and political functionaries.",
    effects:
      "Capital only. First palace built: reduce Unrest by 10. Allows 3 Leadership activities/turn. Ruler gains +3 to Leadership checks.",
    itemBonuses: [
      { activity: 'new-leadership', bonus: 3 },
      { activity: 'pledge-of-fealty-statecraft', bonus: 3 },
      { activity: 'pledge-of-fealty-warfare', bonus: 3 },
      { activity: 'send-diplomatic-envoy', bonus: 3 },
      { activity: 'garrison-army', bonus: 3 },
      { activity: 'recover-army', bonus: 3 },
      { activity: 'recruit-army', bonus: 3 },
    ],
  },
  park: {
    id: 'park',
    name: 'Park',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '5 RP',
    construction: 'Wilderness DC 18',
    upgradeFrom: '',
    upgradeTo: 'menagerie',
    ruin: '',
    description: "A plot of undeveloped land set aside for public use; can be landscaped to taste.",
    effects: "First park each Kingdom turn: reduce Unrest by 1.",
    itemBonuses: [{ activity: 'rest-and-relax-wilderness', bonus: 1 }],
    image: 'park',
  },
  pavedstreets: {
    id: 'pavedstreets',
    name: 'Paved Streets',
    type: 'INFRASTRUCTURE',
    tags: [],
    level: 4,
    lots: 0,
    residential: false,
    cost: '12 RP, 6 Stone',
    construction: 'Industry (trained) DC 19',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Brick or cobblestone streets that speed transportation and ease passage.",
    effects: "Reduces lot-to-lot travel time to 5 minutes (from 15).",
  },
  pier: {
    id: 'pier',
    name: 'Pier',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '16 RP, 2 Lumber',
    construction: 'Boating DC 18',
    upgradeFrom: '',
    upgradeTo: 'waterfront',
    ruin: '',
    description: "Wooden piers allowing easy access to fishing and a place to moor boats.",
    effects: "Must be built on a lot next to a Water border.",
    itemBonuses: [{ activity: 'go-fishing', bonus: 1 }],
    image: 'pier',
  },
  rubble: {
    id: 'rubble',
    name: 'Rubble',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 0,
    lots: 1,
    residential: false,
    cost: '—',
    construction: '—',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "An unsightly heap of rubble fills this lot.",
    effects: "Created by failed events or critical-failed Demolish. Cannot be built on; must be Demolished to clear.",
    image: 'rubble',
  },
  sacredgrove: {
    id: 'sacredgrove',
    name: 'Sacred Grove',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 5,
    lots: 1,
    residential: false,
    cost: '36 RP',
    construction: 'Wilderness (trained) DC 20',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Untouched land blessed by spirits, druids, or allied fey.",
    effects: "Treat settlement's level as one higher for available primal magic items (stacks up to 3×).",
    itemBonuses: [{ activity: 'quell-unrest-folklore', bonus: 1 }],
    traditionBonuses: { primal: 1 },
    image: 'sacredgrove',
  },
  securewarehouse: {
    id: 'securewarehouse',
    name: 'Secure Warehouse',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 6,
    lots: 2,
    residential: false,
    cost: '24 RP, 6 Lumber, 4 Ore, 6 Stone',
    construction: 'Industry (expert) DC 22',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A warehouse designed to keep valuables safe.",
    effects: "Each secure warehouse increases your maximum Luxuries commodity capacity by 1.",
    itemBonuses: [{ activity: 'craft-luxuries', bonus: 1 }],
  },
  sewersystem: {
    id: 'sewersystem',
    name: 'Sewer System',
    type: 'INFRASTRUCTURE',
    tags: [],
    level: 7,
    lots: 0,
    residential: false,
    cost: '24 RP, 8 Lumber, 8 Stone',
    construction: 'Engineering (expert) DC 23',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "An underground sanitation system that keeps the settlement clean and disease-free.",
    effects: "Reduces the settlement's Consumption by 1.",
    itemBonuses: [{ activity: 'clandestine-business', bonus: 1 }],
  },
  shrine: {
    id: 'shrine',
    name: 'Shrine',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 1,
    lots: 1,
    residential: false,
    cost: '8 RP, 2 Lumber, 1 Stone',
    construction: 'Folklore (trained) DC 15',
    upgradeFrom: '',
    upgradeTo: 'temple',
    ruin: '',
    description: "A small building devoted to a deity or faith, attended by resident or visiting clergy.",
    effects: "Treat settlement's level as one higher for available divine magic items (stacks up to 3×; not with temples/cathedrals).",
    itemBonuses: [{ activity: 'celebrate-holiday', bonus: 1 }],
    traditionBonuses: { divine: 1 },
    image: 'shrine',
  },
  smithy: {
    id: 'smithy',
    name: 'Smithy',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '8 RP, 2 Lumber, 1 Ore, 1 Stone',
    construction: 'Industry (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Workshops and forges for metalworking.",
    effects: "+1 item bonus to Craft checks made to work with metal.",
    itemBonuses: [
      { activity: 'craft-metal', bonus: 1 },
      { activity: 'trade-commodities', bonus: 1 },
      { activity: 'outfit-army', bonus: 1 },
    ],
    image: 'smithy',
  },
  specialartisan: {
    id: 'specialartisan',
    name: 'Specialized Artisan',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 4,
    lots: 1,
    residential: false,
    cost: '10 RP, 4 Lumber, 1 Luxury',
    construction: 'Trade (expert) DC 19',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Shops and homes of crafters of fine jewelry, glassware, clockworks, and the like.",
    effects: "+1 item bonus to Craft checks made to craft specialized goods like jewelry.",
    itemBonuses: [
      { activity: 'craft-specialized', bonus: 1 },
      { activity: 'craft-luxuries', bonus: 1 },
    ],
    image: 'specialartisan',
  },
  stable: {
    id: 'stable',
    name: 'Stable',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '10 RP, 2 Lumber',
    construction: 'Wilderness (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A yard and smaller structures to house, train, and sell mounts.",
    effects: "+1 item bonus to Establish Trade Agreement.",
    itemBonuses: [{ activity: 'establish-trade-agreement', bonus: 1 }],
    image: 'stable',
  },
  stockyard: {
    id: 'stockyard',
    name: 'Stockyard',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 3,
    lots: 4,
    residential: false,
    cost: '20 RP, 4 Lumber',
    construction: 'Industry DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "Several barns and pens used to house livestock and prepare them for slaughter.",
    effects: "A settlement with at least one stockyard reduces Consumption by 1.",
    itemBonuses: [{ activity: 'gather-livestock', bonus: 1 }],
  },
  stonemason: {
    id: 'stonemason',
    name: 'Stonemason',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 3,
    lots: 2,
    residential: false,
    cost: '16 RP, 2 Lumber',
    construction: 'Industry (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A large building used to store and work quarried stone for construction.",
    effects: "Each stonemason in your kingdom increases maximum Stone commodity capacity by 1.",
    itemBonuses: [{ activity: 'establish-work-site-quarry', bonus: 1 }],
  },
  tannery: {
    id: 'tannery',
    name: 'Tannery',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '6 RP, 2 Lumber',
    construction: 'Industry (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A factory outfitted with racks, vats, and tools for preparing hides and leather.",
    effects: "Cannot share a block with any Residential structure except tenements.",
    itemBonuses: [{ activity: 'trade-commodities', bonus: 1 }],
    image: 'tannery',
  },
  taverndive: {
    id: 'taverndive',
    name: 'Tavern, Dive',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 1,
    lots: 1,
    residential: false,
    cost: '12 RP, 1 Lumber',
    construction: 'Trade (trained) DC 15',
    upgradeFrom: '',
    upgradeTo: 'tavern, popular',
    ruin: '',
    description: "A rough-and-tumble establishment for entertainment, eating, and drinking.",
    effects: "First dive tavern each Kingdom turn: reduce Unrest by 1, increase Crime by 1.",
    image: 'taverndive',
  },
  tavernpopular: {
    id: 'tavernpopular',
    name: 'Tavern, Popular',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '24 RP, 6 Lumber, 2 Stone',
    construction: 'Trade (expert) DC 18',
    upgradeFrom: 'tavern, dive',
    upgradeTo: 'tavern, luxury',
    ruin: '',
    description: "A respectable establishment for entertainment, eating, and drinking.",
    effects: "First popular tavern: reduce Unrest by 2. +1 item bonus to Performance to Earn Income and Gather Information.",
    itemBonuses: [
      { activity: 'performance-earn-income', bonus: 1 },
      { activity: 'gather-information', bonus: 1 },
      { activity: 'hire-adventurers', bonus: 1 },
      { activity: 'rest-and-relax-trade', bonus: 1 },
    ],
    image: 'tavernpopular',
  },
  tavernluxury: {
    id: 'tavernluxury',
    name: 'Tavern, Luxury',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'FAMOUS'],
    level: 9,
    lots: 2,
    residential: false,
    cost: '48 RP, 10 Lumber, 8 Luxuries, 8 Stone',
    construction: 'Trade (master) DC 26',
    upgradeFrom: 'tavern, popular',
    upgradeTo: 'tavern, world-class',
    ruin: '',
    description: "A high-class establishment for entertainment, eating, and drinking.",
    effects: "First luxury tavern: reduce Unrest by 1d4+1. +2 item bonus to Performance to Earn Income and Gather Information.",
    itemBonuses: [
      { activity: 'performance-earn-income', bonus: 2 },
      { activity: 'gather-information', bonus: 2 },
      { activity: 'hire-adventurers', bonus: 2 },
      { activity: 'rest-and-relax-trade', bonus: 2 },
    ],
  },
  tavernworldclass: {
    id: 'tavernworldclass',
    name: 'Tavern, World-Class',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE', 'FAMOUS'],
    level: 15,
    lots: 2,
    residential: false,
    cost: '64 RP, 18 Lumber, 15 Luxuries, 15 Stone',
    construction: 'Trade (master) DC 34',
    upgradeFrom: 'tavern, luxury',
    upgradeTo: '',
    ruin: '',
    description: "A legendary establishment for entertainment, eating, and drinking.",
    effects: "First world-class tavern each Kingdom turn: reduce Unrest by 2d4. +3 item bonus to Performance/Gather Information.",
    itemBonuses: [
      { activity: 'performance-earn-income', bonus: 3 },
      { activity: 'gather-information', bonus: 3 },
      { activity: 'hire-adventurers', bonus: 3 },
      { activity: 'rest-and-relax-trade', bonus: 3 },
      { activity: 'repair-reputation-strife', bonus: 3 },
    ],
  },
  temple: {
    id: 'temple',
    name: 'Temple',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'FAMOUS', 'INFAMOUS'],
    level: 7,
    lots: 2,
    residential: false,
    cost: '32 RP, 6 Lumber, 6 Stone',
    construction: 'Folklore (trained) DC 23',
    upgradeFrom: 'shrine',
    upgradeTo: 'cathedral',
    ruin: '',
    description: "A building devoted to worshipping a deity or faith.",
    effects: "First temple each Kingdom turn: reduce Unrest by 2. Treat level as one higher for divine items (stacks up to 3×; not with shrines/cathedrals).",
    itemBonuses: [
      { activity: 'celebrate-holiday', bonus: 1 },
      { activity: 'provide-care', bonus: 1 },
    ],
    traditionBonuses: { divine: 1 },
  },
  tenement: {
    id: 'tenement',
    name: 'Tenement',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'RESIDENTIAL'],
    level: 0,
    lots: 1,
    residential: true,
    cost: '1 RP, 1 Lumber',
    construction: 'Industry DC 14',
    upgradeFrom: '',
    upgradeTo: 'houses',
    ruin: '+1 to a Ruin of your choice',
    description: "Hastily-built shantytowns of tightly packed, multi-family dwellings — cheap and fast.",
    effects: "First tenements each Kingdom turn: reduce Unrest by 1.",
    image: 'tenement',
  },
  theater: {
    id: 'theater',
    name: 'Theater',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 9,
    lots: 2,
    residential: false,
    cost: '24 RP, 8 Lumber, 3 Stone',
    construction: 'Arts (expert) DC 26',
    upgradeFrom: 'festival hall',
    upgradeTo: 'opera house',
    ruin: '',
    description: "A venue for concerts, plays, and dances, doubling as a venue for debates or other events.",
    effects: "First theater each Kingdom turn: reduce Unrest by 1. +2 item bonus to Performance to Earn Income.",
    itemBonuses: [
      { activity: 'performance-earn-income', bonus: 2 },
      { activity: 'celebrate-holiday', bonus: 2 },
    ],
  },
  thievesguild: {
    id: 'thievesguild',
    name: "Thieves' Guild",
    type: 'STRUCTURE',
    tags: ['BUILDING', 'INFAMOUS'],
    level: 5,
    lots: 1,
    residential: false,
    cost: '25 RP, 4 Lumber',
    construction: 'Intrigue (trained) DC 20',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '+1 Crime',
    description: "The government knows this group exists but allows it to continue, within limits.",
    effects: "+1 item bonus to Create Forgeries.",
    itemBonuses: [
      { activity: 'create-forgeries', bonus: 1 },
      { activity: 'infiltration', bonus: 1 },
    ],
    image: 'thievesguild',
  },
  townhall: {
    id: 'townhall',
    name: 'Town Hall',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE'],
    level: 2,
    lots: 2,
    residential: false,
    cost: '22 RP, 4 Lumber, 4 Stone',
    construction: 'Defense / Industry / Magic / Statecraft (trained) DC 16',
    upgradeFrom: '',
    upgradeTo: 'castle',
    ruin: '',
    description: "A public venue for town meetings and a repository for town history and records.",
    effects: "First town hall each Kingdom turn: reduce Unrest by 1. In a capital, allows 3 Leadership activities/turn.",
  },
  tradeshop: {
    id: 'tradeshop',
    name: 'Trade Shop',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '10 RP, 2 Lumber',
    construction: 'Trade (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: 'guildhall',
    ruin: '',
    description: "A store focused on providing services. Specify the kind (bakery, carpenter, tailor, etc.) when built.",
    effects: "+1 item bonus to associated Crafting checks while in this settlement.",
    itemBonuses: [
      { activity: 'craft-trade', bonus: 1 },
      { activity: 'purchase-commodities', bonus: 1 },
    ],
    image: 'tradeshop',
  },
  university: {
    id: 'university',
    name: 'University',
    type: 'STRUCTURE',
    tags: ['BUILDING', 'EDIFICE', 'FAMOUS'],
    level: 15,
    lots: 4,
    residential: false,
    cost: '78 RP, 18 Lumber, 18 Luxuries, 18 Stone',
    construction: 'Scholarship (master) DC 34',
    upgradeFrom: 'academy',
    upgradeTo: '',
    ruin: '',
    description: "A sprawling institution of higher learning.",
    effects: "+3 item bonus to Lore checks to Recall Knowledge while Investigating, to Research, and to Decipher Writing.",
    itemBonuses: [
      { activity: 'recall-knowledge-investigating', bonus: 3 },
      { activity: 'researching', bonus: 3 },
      { activity: 'decipher-writing', bonus: 3 },
      { activity: 'creative-solution', bonus: 3 },
    ],
  },
  watchtower: {
    id: 'watchtower',
    name: 'Watchtower',
    type: 'STRUCTURE',
    tags: ['BUILDING'],
    level: 3,
    lots: 1,
    residential: false,
    cost: '12 RP, 4 Lumber or 4 Stone',
    construction: 'Defense (trained) DC 18',
    upgradeFrom: '',
    upgradeTo: '',
    ruin: '',
    description: "A guard post that grants advance warning to upcoming dangerous events.",
    effects: "First watchtower each Kingdom turn: reduce Unrest by 1.",
    image: 'watchtower',
  },
  waterfront: {
    id: 'waterfront',
    name: 'Waterfront',
    type: 'STRUCTURE',
    tags: ['YARD'],
    level: 8,
    lots: 4,
    residential: false,
    cost: '90 RP, 10 Lumber',
    construction: 'Boating (expert) DC 24',
    upgradeFrom: 'pier',
    upgradeTo: '',
    ruin: '',
    description: "A bustling port for waterborne passengers and cargo, with shipping and shipbuilding facilities.",
    effects: "Must be next to a Water Border. Increases settlement's effective level by 1 for purchases.",
    itemBonuses: [
      { activity: 'go-fishing', bonus: 2 },
      { activity: 'establish-trade-agreement', bonus: 2 },
      { activity: 'rest-and-relax-boating', bonus: 2 },
    ],
    traditionBonuses: { base: 1 },
  },
  woodenwall: {
    id: 'woodenwall',
    name: 'Wall, Wooden',
    type: 'INFRASTRUCTURE',
    tags: [],
    level: 1,
    lots: 0,
    residential: false,
    cost: '2 RP, 4 Lumber',
    construction: 'Defense DC 15',
    upgradeFrom: '',
    upgradeTo: 'wall, stone',
    ruin: '',
    description: "Wooden walls provide serviceable defenses to a settlement border.",
    effects: "First wooden wall in this settlement: reduce Unrest by 1.",
  },
  stonewall: {
    id: 'stonewall',
    name: 'Wall, Stone',
    type: 'INFRASTRUCTURE',
    tags: [],
    level: 5,
    lots: 0,
    residential: false,
    cost: '4 RP, 8 Stone',
    construction: 'Defense (trained) DC 20',
    upgradeFrom: 'wall, wooden',
    upgradeTo: '',
    ruin: '',
    description: "Stone walls provide solid defenses to a settlement's border.",
    effects: "First stone wall in this settlement: reduce Unrest by 1.",
  },
};

// =============================================================
// Lookup helpers
// =============================================================

/**
 * Runtime-loaded image overrides. Populated by main.ts on plugin load by
 * scanning the plugin's `building_images/` folder. Keys are building ids
 * (matching `BuildingMetadata.id`), values are data URLs.
 *
 * This lets users drop personal-use building tokens into their plugin
 * folder without rebuilding the bundle. Overrides take precedence over
 * the build-time inlined images.
 */
export const BUILDING_IMAGE_OVERRIDES: Record<string, string> = {};

export function setImageOverride(buildingId: string, dataUrl: string): void {
  BUILDING_IMAGE_OVERRIDES[buildingId] = dataUrl;
}

export function clearImageOverrides(): void {
  for (const k of Object.keys(BUILDING_IMAGE_OVERRIDES)) delete BUILDING_IMAGE_OVERRIDES[k];
}

export function allBuildings(): BuildingMetadata[] {
  return Object.values(BUILDINGS).sort((a, b) => a.name.localeCompare(b.name));
}

export function buildingsForFootprint(lotCount: 1 | 2 | 4, maxKingdomLevel = 99): BuildingMetadata[] {
  return allBuildings().filter(b => b.lots === lotCount && b.level <= maxKingdomLevel);
}

export function imageFor(buildingId: string): string {
  // Override first (runtime-loaded), then bundled image (build-time inlined)
  const override = BUILDING_IMAGE_OVERRIDES[buildingId];
  if (override) return override;
  const meta = BUILDINGS[buildingId];
  if (!meta?.image) return '';
  return BUILDING_IMAGES[meta.image] || '';
}
